Globomantics/Components/CreditCardRatesViewComponent.cs
using Globomantics.Core.Models;
using Globomantics.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Globomantics.Components
{
    public class CreditCardRatesViewComponent : ViewComponent
    {
        private IRateService rateService;

        public CreditCardRatesViewComponent(IRateService rateService)
        {
            this.rateService = rateService;
        }

        public async Task<IViewComponentResult> InvokeAsync(
            string title, string subtitle)
        {
            var ratesVM = new CreditCardWidgetVM()
            {
                Rates = rateService.GetCreditCardRates(),
                WidgetTitle = title,
                WidgetSubTitle = subtitle
            };

            return View(ratesVM);
        }
    }

    // TODO: Move to external class
    public class CreditCardWidgetVM
    {
        public string WidgetTitle { get; set; }
        public string WidgetSubTitle { get; set; }
        public List<Rate> Rates { get; set; }
    }
}

Globomantics/Components/MortgageRatesViewComponent.cs
using Globomantics.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Globomantics.Components
{
    public class MortgageRatesViewComponent : ViewComponent
    {
        private IRateService rateService;

        public MortgageRatesViewComponent(IRateService rateService)
        {
            this.rateService = rateService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var rates = rateService.GetMortgageRates();

            return View(rates);
        }
    }
}

Globomantics/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Globomantics.Models;
using Globomantics.Services;
using Globomantics.Core.Models;
using Globomantics.Constraints;

namespace Globomantics.Controllers
{
    public class HomeController : Controller
    {
        private IRateService rateService;

        public HomeController(IRateService rateService)
        {
            this.rateService = rateService;
        }

        [Route("")]
        [Route("home/index")]
        public IActionResult Index()
        {
            return View();
        }

        [MobileSelector]
        [Route("")]
        [Route("home/index")]
        public IActionResult MobileIndex()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Globomantics/Views/Themes/Beta/Home/Index.cshtml
<h1>This came from beta!</h1>
<div class="container marketing">
    <div class="row">
        <div class="col-md-4">
            <h3>CD Rates</h3>
            <p class="lead">The Longer you Save, the More You Earn</p>
            <cdrate title="12 Month CD" term-length="Months12" meter-percent="50"></cdrate>
            <cdrate title="18 Month CD" term-length="Months18" meter-percent="75"></cdrate>
            <cdrate title="24 Month CD" term-length="Months24" meter-percent="100"></cdrate>
        </div>
        <div class="col-md-4">
            @await  Component.InvokeAsync("MortgageRates")
        </div>
        <div class="col-md-4">
            @await  Component.InvokeAsync("CreditCardRates",
               new {
                   title = "Credit Card Rates",
                   subtitle = "The best rates around."
               })
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row">
        <div class="col-md-4">
            <h3>Retire Early</h3>
            <div class="card mb-4 box-shadow">
                <div style="height: 225px; width: 100%">
                    <img class="card-img-top" style="height: auto; width: 100%; display: block;" src="~/images/small/bench.jpg" data-holder-rendered="true">
                </div>
                <div class="card-body">
                    <p class="card-text">Take that vacation you always wanted.  Learn about retirement options and planning.</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">Learn More</button>
                        </div>
                        <small class="text-muted">9 mins</small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <h3>Jump In</h3>
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" style="height: auto; width: 100%; display: block;" src="~/images/small/shore.jpg" data-holder-rendered="true">
                <div class="card-body">
                    <p class="card-text">Open a checking account and receive $500 cash. There's never been a better time to join.</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">Learn More</button>
                        </div>
                        <small class="text-muted">9 mins</small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <h3>A Time to Grow</h3>
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" style="height: auto; width: 100%; display: block;" src="~/images/small/trees.jpg" data-holder-rendered="true">
                <div class="card-body">
                    <p class="card-text">Don't let your money sit in savings.  Learn about our options to grow your investments.</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">Learn More</button>
                        </div>
                        <small class="text-muted">9 mins</small>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">Stop. <span class="text-muted">Take some time to look ahead.</span></h2>
            <p class="lead">Finances are all about planning.  Our investors care about your future - we'll help you navigate new roads.  Learn about out personal consulting options today.</p>
            <p class="lead">We believe in our expertise - we'll even guarantee a return.</p>
            <button class="btn btn-primary float-right">Get Started</button>"
        </div>
        <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" src="~/images/stop.jpg" alt="Generic placeholder image">
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">Stay engaged. <span class="text-muted">Keep your finances on track.</span></h2>
            <p class="lead">We can help you learn simple tips for staying on budget and on track for your monthly expenses.  Attend one of our seminars today!</p>
            <button class="btn btn-primary float-right">Get Started</button>"
        </div>
        <div class="col-md-5 order-md-1">
            <img class="featurette-image img-fluid mx-auto" src="~/images/small/train.jpg" alt="Generic placeholder image">
        </div>
    </div>
</div>